version = 1

[[analyzers]]
name = "javascript"
enabled = true

[[analyzers]]
name = "test-coverage"
enabled = true

[[analyzers]]
name = "sql"
enabled = true

[[transformers]]
name = "prettier"
enabled = true